theme = "ayu_dark"

[editor]
line-number = "absolute"
mouse = true
scrolloff = 10
completion-trigger-len = 1
true-color = true
idle-timeout = 50
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-type", "file-name"]
right = ["diagnostics", "position"]

[editor.soft-wrap]
enable = true

[keys.normal]
H = "goto_previous_buffer"
L = "goto_next_buffer"
space.x = ":buffer-close"
space.w = ":w"